### ISSUE TITLE
certbot --apache error:Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA

### ISSUE THREAD

**Issue by Upo** [reillychase/UniFi-Controller-LetsEncrypt-Apache#5]
certbot --apache exits with error: Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA
Cause is that Let’s Encrypt permanently disabled the TLS-SNI-01 challenge due to a security report, as of 2018-01-09 and jessie-backports contains certbot version 0.10.2 which is way too old and not working. You need at least certbot 0.21.0 to work flawlessly.

Source: [https://community.letsencrypt.org/t/solution-client-with-the-currently-selected-authenticator-does-not-support-any-combination-of-challenges-that-will-satisfy-the-ca/49983](url)

Fortunately debian unstable has version 0.21.1 now. So if we change jessie-backports to unstable in the certbot install section then we will install a working certbot version.
So replace "Install Let's Encrypt certbot" with this:

```
echo 'deb http://ftp.debian.org/debian unstable main' | sudo tee /etc/apt/sources.list.d/unstable.list
sudo apt-get update
sudo apt-get install python-certbot-apache -t unstable
```

**Comment by reillychase** [comment]
Sweet! Really appreciate this, thanks
